### ISSUE TITLE
Add configurable sound range to DoNoiseAlert AI behaviour

### ISSUE THREAD

**Issue by MalucoMarinero** [X2CommunityCore/X2CommunityHighlander#21]

**Comment by robojumper** [comment]
Currenltly, `X2AIBTDefaultActions.BuildVisualizationForNoiseAlert` shows a "Yelling" flyover even though the yelling has a sound range of 0 (not configured).

It might be worth changing that so people don't get confused about all civvies yelling, thinking this is an LW2 thing (because it's not, it's just a fix for vanilla behavior).
