### ISSUE TITLE
Xcom 2 collection on Android

### ISSUE THREAD

**Issue by tourmz** [X2CommunityCore/X2CommunityHighlander#290]
Hi could somebody please cook this mod for Android, I have gotten some mods to work so I know it does except mods. However most good content needs highlander and I am unable to load it with noseekfreeloading.

**Comment by Iridar** [comment]
It's a miracle any mods can be used on Android at all, considering this interaction was never intended by developers. 

We cannot do anything about Highlander being incompatible with Android, because we don't have access to the source code of the Android version of the game. It's the same problem as with the Epic Store version.
